#!/bin/bash

# Test script to send an email from

base_url="$1"
email="$2"
authorization_token="$3"

if [ -z "$base_url" ] || [ -z "$email" ] || [ -z "$authorization_token" ]; then
  echo "Usage: ./send_email.sh <base_url> <to_email_address> <authorization_token>"
  exit 1
fi

url="$base_url/api/test/send-email"

payload='{
  "email": "'"$email"'"
}'

curl -X POST \
  -H "Authorization: $authorization_token" \
  -H "Content-Type: application/json" \
  -d "$payload" \
  "$url"
